#define GENERATE_BUTTON_PARAM 101
#define NEXTPAGE_BUTTON_PARAM 102
#define PREVPAGE_BUTTON_PARAM 103
#define SORTPAGE_BUTTON_PARAM 104
#define SORTALL_BUTTON_PARAM  105
#define WRITE_TO_FILE_PARAM   106
#define PREV_PAGE_PARAM       108
#define NEXT_PAGE_PARAM       109

#define LENGTH_EDIT_PARAM 201
#define J_EDIT_PARAM      202
#define K_EDIT_PARAM      203
#define MOD_EDIT_PARAM    204
#define SEED_EDIT_PARAM   205

#define MAX_INPUT 36